#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bugfix)\/[a-z0-9._-]+$"

message="Please use the following format for the branch name: $valid_branch_regex. Your push will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0